-- ============================================================
-- QR Scan System for Garbage Collection Verification
-- ============================================================

-- Table: dustbin_qr_codes
-- Stores QR codes generated by vehicles/drivers for dustbins
CREATE TABLE IF NOT EXISTS public.dustbin_qr_codes (
  id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  qr_code           TEXT UNIQUE NOT NULL,
  vehicle_id        UUID REFERENCES public.vehicles(id) ON DELETE SET NULL,
  driver_id         UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  bin_location_lat  NUMERIC(10, 7),
  bin_location_lng  NUMERIC(10, 7),
  bin_address       TEXT,
  is_active         BOOLEAN DEFAULT TRUE,
  generated_at      TIMESTAMPTZ DEFAULT NOW(),
  expires_at        TIMESTAMPTZ, -- Optional: QR code expiration
  
  CONSTRAINT unique_qr_code UNIQUE(qr_code)
);

-- Table: qr_scan_logs
-- Records every scan by citizens with photo and location proof
CREATE TABLE IF NOT EXISTS public.qr_scan_logs (
  id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  qr_code_id        UUID NOT NULL REFERENCES public.dustbin_qr_codes(id) ON DELETE CASCADE,
  citizen_id        UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  citizen_name      TEXT,
  citizen_email     TEXT,
  
  -- Photo evidence
  garbage_image_url TEXT NOT NULL,
  
  -- Location data
  scan_latitude     NUMERIC(10, 7) NOT NULL,
  scan_longitude    NUMERIC(10, 7) NOT NULL,
  scan_address      TEXT,
  
  -- Metadata
  scan_timestamp    TIMESTAMPTZ DEFAULT NOW(),
  device_info       TEXT,
  
  -- Verification status
  verified_by_admin BOOLEAN DEFAULT FALSE,
  admin_notes       TEXT,
  
  created_at        TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_qr_codes_vehicle     ON public.dustbin_qr_codes(vehicle_id);
CREATE INDEX IF NOT EXISTS idx_qr_codes_driver      ON public.dustbin_qr_codes(driver_id);
CREATE INDEX IF NOT EXISTS idx_qr_codes_active      ON public.dustbin_qr_codes(is_active);
CREATE INDEX IF NOT EXISTS idx_qr_codes_qr          ON public.dustbin_qr_codes(qr_code);

CREATE INDEX IF NOT EXISTS idx_scan_logs_qr_code    ON public.qr_scan_logs(qr_code_id);
CREATE INDEX IF NOT EXISTS idx_scan_logs_citizen    ON public.qr_scan_logs(citizen_id);
CREATE INDEX IF NOT EXISTS idx_scan_logs_timestamp  ON public.qr_scan_logs(scan_timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_scan_logs_verified   ON public.qr_scan_logs(verified_by_admin);

-- Storage bucket for QR scan images
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'qr-scan-photos',
  'qr-scan-photos',
  true,
  10485760, -- 10MB
  ARRAY['image/jpeg', 'image/png', 'image/webp', 'image/jpg']
)
ON CONFLICT (id) DO NOTHING;

-- Drop existing policies if they exist (to avoid conflicts)
DROP POLICY IF EXISTS "qr_scan_photos: auth upload" ON storage.objects;
DROP POLICY IF EXISTS "qr_scan_photos: public read" ON storage.objects;

-- Storage policy: Anyone authenticated can upload
CREATE POLICY "qr_scan_photos: auth upload"
  ON storage.objects FOR INSERT
  TO authenticated
  WITH CHECK (bucket_id = 'qr-scan-photos');

-- Storage policy: Anyone can view
CREATE POLICY "qr_scan_photos: public read"
  ON storage.objects FOR SELECT
  TO public
  USING (bucket_id = 'qr-scan-photos');

-- Enable RLS
ALTER TABLE public.dustbin_qr_codes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.qr_scan_logs ENABLE ROW LEVEL SECURITY;

-- Drop existing RLS policies if they exist (to avoid conflicts)
DROP POLICY IF EXISTS "qr_codes: driver own" ON public.dustbin_qr_codes;
DROP POLICY IF EXISTS "qr_codes: admin all" ON public.dustbin_qr_codes;
DROP POLICY IF EXISTS "qr_codes: citizen read" ON public.dustbin_qr_codes;
DROP POLICY IF EXISTS "qr_codes: vehicle_authority read" ON public.dustbin_qr_codes;
DROP POLICY IF EXISTS "scan_logs: citizen insert" ON public.qr_scan_logs;
DROP POLICY IF EXISTS "scan_logs: citizen own" ON public.qr_scan_logs;
DROP POLICY IF EXISTS "scan_logs: admin all" ON public.qr_scan_logs;
DROP POLICY IF EXISTS "scan_logs: driver own" ON public.qr_scan_logs;
DROP POLICY IF EXISTS "scan_logs: vehicle_authority view" ON public.qr_scan_logs;

-- RLS Policies for dustbin_qr_codes

-- Drivers can create and view their own QR codes
CREATE POLICY "qr_codes: driver own"
  ON public.dustbin_qr_codes FOR ALL
  USING (
    EXISTS (
      SELECT 1 FROM public.profiles p
      WHERE p.id = auth.uid() AND p.role IN ('driver', 'vehicle_authority') AND driver_id = p.id
    )
  );

-- Admins can manage all QR codes
CREATE POLICY "qr_codes: admin all"
  ON public.dustbin_qr_codes FOR ALL
  USING (
    EXISTS (
      SELECT 1 FROM public.profiles p
      WHERE p.id = auth.uid() AND p.role = 'admin'
    )
  );

-- Citizens can view active QR codes (for scanning)
CREATE POLICY "qr_codes: citizen read"
  ON public.dustbin_qr_codes FOR SELECT
  USING (
    is_active = true AND
    EXISTS (
      SELECT 1 FROM public.profiles p
      WHERE p.id = auth.uid() AND p.role = 'citizen'
    )
  );

-- Vehicle Authority can view QR codes for their vehicles
CREATE POLICY "qr_codes: vehicle_authority read"
  ON public.dustbin_qr_codes FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM public.profiles p
      JOIN public.vehicles v ON v.authority_id = p.id
      WHERE p.id = auth.uid() 
        AND p.role = 'vehicle_authority'
        AND v.id = dustbin_qr_codes.vehicle_id
    )
  );

-- RLS Policies for qr_scan_logs

-- Citizens can insert their own scans
CREATE POLICY "scan_logs: citizen insert"
  ON public.qr_scan_logs FOR INSERT
  WITH CHECK (
    auth.uid() = citizen_id AND
    EXISTS (
      SELECT 1 FROM public.profiles p
      WHERE p.id = auth.uid() AND p.role = 'citizen'
    )
  );

-- Citizens can view their own scans
CREATE POLICY "scan_logs: citizen own"
  ON public.qr_scan_logs FOR SELECT
  USING (
    auth.uid() = citizen_id
  );

-- Admins can view and manage all scans
CREATE POLICY "scan_logs: admin all"
  ON public.qr_scan_logs FOR ALL
  USING (
    EXISTS (
      SELECT 1 FROM public.profiles p
      WHERE p.id = auth.uid() AND p.role = 'admin'
    )
  );

-- Drivers can view scans related to their QR codes
CREATE POLICY "scan_logs: driver own"
  ON public.qr_scan_logs FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM public.dustbin_qr_codes qr
      JOIN public.profiles p ON p.id = qr.driver_id
      WHERE qr.id = qr_scan_logs.qr_code_id 
        AND p.id = auth.uid() 
        AND p.role IN ('driver', 'vehicle_authority')
    )
  );

-- Vehicle Authority can view scans for their managed vehicles
CREATE POLICY "scan_logs: vehicle_authority view"
  ON public.qr_scan_logs FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM public.dustbin_qr_codes qr
      JOIN public.vehicles v ON v.id = qr.vehicle_id
      JOIN public.profiles p ON p.id = v.authority_id
      WHERE qr.id = qr_scan_logs.qr_code_id 
        AND p.id = auth.uid() 
        AND p.role = 'vehicle_authority'
    )
  );

-- Function: Auto-cleanup expired QR codes
CREATE OR REPLACE FUNCTION cleanup_expired_qr_codes()
RETURNS void AS $$
BEGIN
  UPDATE public.dustbin_qr_codes
  SET is_active = false
  WHERE expires_at IS NOT NULL 
    AND expires_at < NOW() 
    AND is_active = true;
END;
$$ LANGUAGE plpgsql;

COMMENT ON TABLE public.dustbin_qr_codes IS 'QR codes generated by vehicles for dustbin verification';
COMMENT ON TABLE public.qr_scan_logs IS 'Logs of citizen scans with photo and location proof';
